version: '3.8'

services:
  validator1:
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 36657:26657
      - 36656:26656

  validator2:
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 46657:26657
      - 46656:26656
