version: "3.8"

services:
  first_node:
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile

  second_node:
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
