btc_relayer = [
  "https://btc.relayer.orai.io:443",
]
state_sync_rpc = [
  "http://3.144.94.154:26667",
  "http://3.144.94.154:26667",
]
tendermint_flags = [
  "--p2p.seeds",
  """
      ffb810640af82a8bd42759ddd46585929da792fd@3.144.94.154:26656
    """,
]

legacy_version = "8.0.x"

genesis = """
{
  "genesis_time": "2024-03-05T23:26:47.43861815Z",
  "chain_id": "oraibtc-mainnet-1",
  "initial_height": "1",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age_num_blocks": "100000",
      "max_age_duration": "172800000000000",
      "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": ["ed25519"]
    },
    "version": {}
  },
  "validators": [],
  "app_hash": ""
}
"""
