[global]
log_level = "info"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 0
clear_on_start = true
tx_confirmation = true
auto_register_counterparty_payee = false

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[[chains]]
id = "Oraichain"
rpc_addr = "https://rpc.orai.io:443"
grpc_addr = "http://grpc.orai.io:9090"
event_source = { mode = 'pull' }
rpc_timeout = "20s"
account_prefix = "orai"
key_name = "relayer"
store_prefix = "ibc"
max_gas = 100000000
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
gas_price = { price = 0.001, denom = 'orai' }
clock_drift = "20s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
# [chains.packet_filter]
# policy = "allow"
# list = [["transfer", "channel-170"],["transfer", "channel-174"]]

[[chains]]
id = 'oraibtc-subnet-1'
rpc_addr = 'http://localhost:26657'
event_source = { mode = 'pull' }
grpc_addr = 'http://localhost:9001'
rpc_timeout = '20s'
account_prefix = 'oraibtc'
key_name = 'relayer'
store_prefix = 'ibc'
max_gas = 100000000
gas_price = { price = 0, denom = 'uoraibtc' }
clock_drift = '20s'
trusting_period = '9days'
max_msg_num = 30
proof_specs = '''
[
  {
    "inner_spec": {
      "child_order": [
        0,
        1,
        2
      ],
      "child_size": 32,
      "empty_child": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "min_prefix_length": 1,
      "max_prefix_length": 1,
      "hash": 6
    },
    "leaf_spec": {
      "hash": 6,
      "prehash_key": 0,
      "prehash_value": 0,
      "length": 4,
      "prefix": "AA"
    },
    "max_depth": 0,
    "min_depth": 0
  },
  {
    "inner_spec": {
      "child_order": [
        0
      ],
      "child_size": 32,
      "empty_child": "",
      "min_prefix_length": 0,
      "max_prefix_length": 0,
      "hash": 6
    },
    "leaf_spec": {
      "hash": 6,
      "prehash_key": 0,
      "prehash_value": 0,
      "length": 0,
      "prefix": ""
    },
    "max_depth": 0,
    "min_depth": 0
  }
]
'''

[chains.trust_threshold]
numerator = '1'
denominator = '3'
#[chains.packet_filter]
#policy = 'allow'
#list = [['transfer', 'channel-1']]

# SUCCESS Channel {
#     ordering: Unordered,
#     a_side: ChannelSide {
#         chain: BaseChainHandle {
#             chain_id: ChainId {
#                 id: "oraibtc-testnet-2",
#                 version: 2,
#             },
#             runtime_sender: Sender { .. },
#         },
#         client_id: ClientId(
#             "07-tendermint-0",
#         ),
#         connection_id: ConnectionId(
#             "connection-0",
#         ),
#         port_id: PortId(
#             "transfer",
#         ),
#         channel_id: Some(
#             ChannelId(
#                 "channel-0",
#             ),
#         ),
#         version: None,
#     },
#     b_side: ChannelSide {
#         chain: BaseChainHandle {
#             chain_id: ChainId {
#                 id: "Oraichain",
#                 version: 0,
#             },
#             runtime_sender: Sender { .. },
#         },
#         client_id: ClientId(
#             "07-tendermint-150",
#         ),
#         connection_id: ConnectionId(
#             "connection-114",
#         ),
#         port_id: PortId(
#             "wasm.orai195269awwnt5m6c843q6w7hp8rt0k7syfu9de4h0wz384slshuzps8y7ccm",
#         ),
#         channel_id: Some(
#             ChannelId(
#                 "channel-184",
#             ),
#         ),
#         version: None,
#     },
#     connection_delay: 0ns,
# }
