[global]
log_level = "info"

[mode.clients]
enabled = true
misbehaviour = true
refresh = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
auto_register_counterparty_payee = false
clear_interval = 0
clear_on_start = true
enabled = true
tx_confirmation = true

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
buckets = 10
end = 20000
start = 500

[telemetry.buckets.latency_confirmed]
buckets = 10
end = 30000
start = 1000

[[chains]]
account_prefix = "orai"
ccv_consumer_chain = false
clock_drift = "20s"
event_source = {mode = 'pull'}
gas_multiplier = 1.5
gas_price = {price = 0.001, denom = 'orai'}
grpc_addr = "http://grpc.orai.io:9090"
id = "Oraichain"
key_name = "relayer"
max_block_time = "30s"
max_gas = 100000000
max_grpc_decoding_size = 33554432
max_msg_num = 30
max_tx_size = 180000
memo_prefix = ""
rpc_addr = "https://rpc.orai.io:443"
rpc_timeout = "20s"
sequential_batch_tx = false
store_prefix = "ibc"
trust_threshold = {numerator = '1', denominator = '3'}
trusting_period = '9days'
[chains.packet_filter]
list = [["transfer", "channel-238"]]
policy = "allow"

[[chains]]
account_prefix = 'oraibtc'
clock_drift = '20s'
event_source = {mode = 'pull'}
gas_price = {price = 0, denom = 'uoraibtc'}
grpc_addr = 'http://localhost:9001'
id = 'oraibtc-testnet-1'
key_name = 'relayer'
max_gas = 100000000
max_msg_num = 30
proof_specs = '''
[
  {
    "inner_spec": {
      "child_order": [
        0,
        1,
        2
      ],
      "child_size": 32,
      "empty_child": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "min_prefix_length": 1,
      "max_prefix_length": 1,
      "hash": 6
    },
    "leaf_spec": {
      "hash": 6,
      "prehash_key": 0,
      "prehash_value": 0,
      "length": 4,
      "prefix": "AA"
    },
    "max_depth": 0,
    "min_depth": 0
  },
  {
    "inner_spec": {
      "child_order": [
        0
      ],
      "child_size": 32,
      "empty_child": "",
      "min_prefix_length": 0,
      "max_prefix_length": 0,
      "hash": 6
    },
    "leaf_spec": {
      "hash": 6,
      "prehash_key": 0,
      "prehash_value": 0,
      "length": 0,
      "prefix": ""
    },
    "max_depth": 0,
    "min_depth": 0
  }
]
'''
rpc_addr = 'http://localhost:26657'
rpc_timeout = '20s'
store_prefix = 'ibc'
trusting_period = '9days'

[chains.trust_threshold]
denominator = '3'
numerator = '1'
#[chains.packet_filter]
#policy = 'allow'
#list = [['transfer', 'channel-1']]
